import {test} from 'node:test'; import assert from 'node:assert/strict'; import '../../integrations/shared/core.js'; const core = globalThis.IDMCore;
test('HTTP validation, sanitization and deduplication',() => { assert.equal(core.links([{url:'https://a.test/f'},{url:'https://a.test/f'}]).length,1); assert.equal(core.validateLink({url:'https://a.test',filename:'a/b'}).filename,'a_b'); for(const url of ['file:///tmp/a','javascript:alert(1)','https://u:p@a.test']) assert.throws(()=>core.validateLink({url})); assert.throws(()=>core.validateLink({url:'https://a.test',headers:{Cookie:'a\r\nb'}})); assert.equal(core.links(Array.from({length:201},(_,i)=>({url:`https://a.test/${i}`}))).length,200); });
for (const status of ['queued','cancelled','error','disconnect']) test(`capture ${status} preserves correct browser state`,async()=> { const calls=[]; const api=Object.fromEntries(['pause','resume','cancel'].map(name=>[name,async()=>calls.push(name)])); const request=async()=> {if(status==='disconnect')throw new Error('lost'); return {status,message:'declined'};}; if(['error','disconnect'].includes(status)) await assert.rejects(core.capture({id:1,url:'https://a.test/f'},api,request)); else await core.capture({id:1,url:'https://a.test/f'},api,request); assert.deepEqual(calls,status==='queued'?['pause','cancel']:['pause','resume']); });
test('capture ignores browser local files',async()=>assert.equal(await core.capture({url:'blob:https://a.test/id'}, {},()=>{}),'ignored'));
test('native response errors are visible',()=> { assert.throws(()=>core.nativeResponse({status:'error',message:'Host missing'}),/Host missing/); assert.throws(()=>core.nativeResponse({status:'wrong'})); });

test('batch deduplication preserves first filename and source page',()=> { const result = core.links([{url:'https://a.test/f',filename:'first',pageURL:'https://a.test/page'},{url:'https://a.test/f',filename:'second'}]); assert.deepEqual(result,[{url:'https://a.test/f',filename:'first',pageURL:'https://a.test/page'}]); });

test('mixed HTTP and Blob collections retain HTTP batch',()=>assert.deepEqual(core.httpLinks([{url:'blob:https://a.test/id'},{url:'https://a.test/f'}]),[{url:'https://a.test/f'}]));
test('site permission patterns omit TCP port',()=> {assert.equal(core.permissionPattern('http://127.0.0.1:5432/path'),'http://127.0.0.1/*'); assert.equal(core.permissionPattern('https://example.com:8443/f'),'https://example.com/*');});
